import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Homepage() {
  return (
    <>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>Homepage</h1>
        </div>
      </main>
    </>
  );
}
